name: CI Workflow for Flask App

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Using Ubuntu to run the workflow

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8 for the Flask app

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the dependencies from requirements.txt

      # Step 4: Run Flask app to test
      - name: Start Flask app in background
        run: |
          nohup python app.py &
          sleep 5  # Wait for a while to ensure the server is up and running

      # Step 5: Test the app is working by making a request
      - name: Test the app
        run: |
          curl http://localhost:8080  # Send a request to the Flask app
        continue-on-error: true  # Allow this to continue even if the test fails

      # Step 6: (Optional) You can add more steps like linting or other tests here

